version: "3.8"

services:
  privnote-vpn:
    container_name: privnote-vpn
    image: qmcgaw/gluetun
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}

  privnote-tor:
    container_name: privnote-tor
    image: goldy/tor-hidden-service:latest
    # network_mode: service:privnote-vpn
    links:
      - privnote-web
    depends_on:
      - privnote-web
    networks:
      - proxy
    environment:
        SERVICE2_TOR_SERVICE_VERSION: '3'
        # hello and again will share the same onion v3 address
        SERVICE2_TOR_SERVICE_HOSTS: 80:privnote-web:3000
        # tor v3 address private key base 64 encoded
        SERVICE2_TOR_SERVICE_KEY: ${TOR_SERVICE_KEY}

  privnote-web:
    container_name: privnote-web
    hostname: privnote-web
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3000
    links:
      - privnote-server
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.privnote-web.rule=Host(`privnote.coding.global`)'
      - 'traefik.http.routers.privnote-web.entrypoints=websecure'
      - 'traefik.http.routers.privnote-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.privnote-web.loadbalancer.server.port=3000'

  privnote-server:
    container_name: privnote-server
    hostname: privnote-server
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    expose:
      - 4000
    depends_on:
      - privnote-db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
    networks:
      - proxy

  privnote-db:
    container_name: privnote-db
    hostname: privnote-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
