version: "3.8"

services:
  privnote-web:
    container_name: privnote-web
    build:
      context: web/
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.privnote-web.rule=Host(`privnote.coding.global`)'
      - 'traefik.http.routers.privnote-web.entrypoints=websecure'
      - 'traefik.http.routers.privnote-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.privnote-web.loadbalancer.server.port=3000'
  privnote-server:
    container_name: privnote-server
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - privnote-db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@privnote-db:5432/${POSTGRES_DB}?schema=public
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.privnote-server.rule=Host(`privnote.coding.global`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.privnote-server.entrypoints=websecure'
      - 'traefik.http.routers.privnote-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.privnote-server.loadbalancer.server.port=${PORT}'
  privnote-db:
    container_name: privnote-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
