[package]
name = "migration"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"


[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }

