[package]
name = "priv_note_entity"
version = "1.0.0"
edition = "2021"

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "0.11.3"
